name = "tenth-avenue-web-design"
compatibility_date = "2026-07-26"
pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "tenth-avenue-leads"
database_id = "b59a4ca9-dce1-4013-878d-58bb07221e66"
